version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    networks:
      - devopsimolasportiva
    ports:
     - 8080:8080
     - 50000:50000
    container_name: jenkins
    volumes:
     - /Users/davidederosa/Desktop/UNIBO/Tirocinio/Jenkins/jenkins_compose/jenkins_configuration:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:7.77.5
    container_name: artifactory
    networks:
      - devopsimolasportiva
    ports:
      - 8082:8082
      - 8081:8081
    volumes:
      - /Users/davidederosa/Desktop/UNIBO/Tirocinio/Jenkins/artifactory/var:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000    

networks:
    devopsimolasportiva:
      driver: bridge