version: '3'

services:
  db:
    image: 'postgres:16'
    environment:
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_DB=imolasportiva
    container_name: db
    secrets:
      - db_password
    networks:
      - imolasportivanetwork
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/

  app:
    image: 'davidederosa24/imolasportiva:${TAG}'
    container_name: imolasportiva
    depends_on:
      - db
    networks:
      - imolasportivanetwork
    ports:
      - "8088:8080"

networks:
    imolasportivanetwork:
      driver: bridge
  
secrets:
    db_password:
     file: db_password.txt